# Generated by Django 5.2.8 on 2025-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Blocked IP",
                "verbose_name_plural": "Blocked IPs",
                "db_table": "blocked_ips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "request_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="request_log_ip_addr_22f98c_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="request_log_timesta_6625f0_idx"
                    ),
                    models.Index(fields=["path"], name="request_log_path_5a9834_idx"),
                ],
            },
        ),
    ]
