# Generated by Django 5.2.8 on 2025-11-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_blockedip_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("high_volume", "High request volume (>100/hour)"),
                            ("sensitive_paths", "Accessing sensitive paths"),
                            ("multiple_reasons", "Multiple suspicious activities"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Suspicious IP",
                "verbose_name_plural": "Suspicious IPs",
                "db_table": "suspicious_ips",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="suspicious__ip_addr_3bcffd_idx"
                    ),
                    models.Index(
                        fields=["detected_at"], name="suspicious__detecte_c5ad7e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="suspicious__is_acti_f1a4ed_idx"
                    ),
                ],
            },
        ),
    ]
